// Generates the "derived KB" artifacts we hand to a Sarvam voice agent.
//
// Sarvam's knowledge base accepts PDF/DOCX/CSV/TSV/TXT/MD files only - there
// is no vector or binary ingest path, and the platform owns embedding,
// chunking and reranking. So our value-add sits entirely upstream: we ingest
// whatever formats we support, apply the tenant's configuration, and emit one
// clean, comprehensive Markdown document for Sarvam to retrieve against.
//
// Deliberately dependency-free (no @/lib/db import) so it stays unit-testable
// - same reasoning as contextBlock.ts, systemPrompt.ts and tenantHost.ts.
//
// THREE artifacts, not one, because they go to three different places in the
// Sarvam agent and mixing them up degrades answers:
//   1. document   -> uploaded as the KB file. Content only.
//   2. description-> the KB's description field. Sarvam's docs are explicit
//                    that "the description is what the agent reads to decide
//                    when to search this KB", so it is a retrieval-quality
//                    lever, not metadata.
//   3. systemPromptAddendum -> pasted into the agent's system prompt. The
//                    tenant's answer-style config must NOT go in the document:
//                    KB content is only surfaced when it is semantically
//                    similar to the caller's question, so style rules buried
//                    there would apply erratically. Style belongs in the
//                    prompt, which is always in context.

export interface DerivedKbSource {
  source_uri: string;
  source_type: string;
  chunks: { text: string; page_or_row: string | null }[];
}

export interface DerivedKbArtifacts {
  document: string;
  description: string;
  systemPromptAddendum: string | null;
  stats: { sourceCount: number; chunkCount: number; characterCount: number };
}

export interface BuildDerivedKbOptions {
  tenantName: string;
  sources: DerivedKbSource[];
  answerConfigMd: string | null;
  generatedAt?: Date;
}

function describeSourceTypes(sources: DerivedKbSource[]): string {
  const types = [...new Set(sources.map((s) => s.source_type))].sort();
  if (types.length === 0) return "documents";
  if (types.length === 1) return `${types[0]} documents`;
  return `${types.slice(0, -1).join(", ")} and ${types[types.length - 1]} documents`;
}

/** Sarvam routes KB selection on this text, so it names the business and lists
 * the actual source files rather than saying something generic like "company
 * knowledge" - specific descriptions are what keep retrieval accurate when an
 * agent has more than one KB attached. */
function buildDescription(tenantName: string, sources: DerivedKbSource[]): string {
  if (sources.length === 0) {
    return `Reference knowledge for ${tenantName}. Currently empty - no source documents have been ingested yet.`;
  }
  const names = sources.map((s) => s.source_uri);
  const shown = names.slice(0, 8).join(", ");
  const more = names.length > 8 ? `, and ${names.length - 8} more` : "";
  return (
    `Reference knowledge for ${tenantName}, compiled from its ${describeSourceTypes(sources)}: ` +
    `${shown}${more}. Search this for factual questions about ${tenantName}'s products, services, ` +
    `policies, procedures and troubleshooting guidance. Do not search it for personal account or ` +
    `order data, which it does not contain.`
  );
}

/** Consecutive identical chunk text is dropped. Chunkers that use overlapping
 * windows would otherwise repeat whole passages in the reassembled document,
 * which wastes Sarvam's storage quota and skews its reranking. */
function dedupeConsecutive(texts: string[]): string[] {
  return texts.filter((t, i) => i === 0 || t.trim() !== texts[i - 1].trim());
}

/** chunkHtmlByHeadings keeps the heading as the first line of the chunk body,
 * so emitting both the "### Heading" and the chunk verbatim prints the heading
 * twice in a row. Strip the echoed first line rather than the heading itself -
 * the heading is the useful structural signal for Sarvam's re-chunking. */
function stripEchoedHeading(text: string, heading: string | null): string {
  if (!heading) return text;
  const lines = text.split("\n");
  if (lines[0]?.trim() === heading.trim()) {
    return lines.slice(1).join("\n").replace(/^\n+/, "");
  }
  return text;
}

export function buildDerivedKb({
  tenantName,
  sources,
  answerConfigMd,
  generatedAt = new Date(),
}: BuildDerivedKbOptions): DerivedKbArtifacts {
  const stamp = generatedAt.toISOString().slice(0, 10);

  const parts: string[] = [
    `# ${tenantName} — Knowledge Base`,
    "",
    `_Generated by MyBizCare on ${stamp}. Do not edit by hand — regenerate from the admin console, ` +
      `because any manual change here is overwritten on the next export._`,
    "",
  ];

  let chunkCount = 0;

  for (const source of sources) {
    parts.push(`## ${source.source_uri}`, "");

    // Group by heading so the document reads like the original rather than a
    // flat wall of chunks - Sarvam re-chunks it anyway, and coherent sections
    // give its reranker better boundaries to work with.
    let currentHeading: string | null | undefined = undefined;
    let buffer: string[] = [];

    const flush = () => {
      if (buffer.length === 0) return;
      if (currentHeading) parts.push(`### ${currentHeading}`, "");
      parts.push(...dedupeConsecutive(buffer), "");
      buffer = [];
    };

    for (const chunk of source.chunks) {
      chunkCount += 1;
      if (chunk.page_or_row !== currentHeading) {
        flush();
        currentHeading = chunk.page_or_row;
      }
      buffer.push(stripEchoedHeading(chunk.text.trim(), chunk.page_or_row).trim());
    }
    flush();
  }

  const document = parts.join("\n").replace(/\n{3,}/g, "\n\n").trimEnd() + "\n";

  return {
    document,
    description: buildDescription(tenantName, sources),
    systemPromptAddendum: answerConfigMd?.trim() ? answerConfigMd.trim() : null,
    stats: {
      sourceCount: sources.length,
      chunkCount,
      characterCount: document.length,
    },
  };
}
